// Api Routes
export const inventoryListApi = 'inventory/inventory-index'
export const applicantStoreApi = 'inventory/inventory-store'
export const applicantUpdateApi = 'inventory/inventory-update'
export const applicantDeleteApi = 'inventory/inventory-delete'
export const productListApi = 'inventory/product-index'
export const productStoreApi = 'inventory/product-store'
export const productUpdateApi = 'inventory/product-update'
export const productStatusUpdateApi = 'inventory/product-status-update'
export const productDeleteApi = 'inventory/product-delete'
export const categoryListApi = 'inventory/category-index'
export const categoryStoreApi = 'inventory/category-index'
export const categoryUpdateApi = 'inventory/category-index'
export const categoryDeleteApi = 'inventory/category-index'
